Bump Poetry to `1.2`
withlogicco/docker-poetry pull request #11
Opened 2022-09-02 08:59 UTC by parisk

2022-09-02 10:01 UTC, akalipetis requested changes
Do we have a reason not to pin the patch version, like we previously did?

Also, let's prefer the official installer.

2022-09-02 10:01 UTC, akalipetis commented on README.md
> +FROM ghcr.io/withlogicco/poetry:1.2
```suggestion
FROM ghcr.io/withlogicco/poetry:1.2.0
```

2022-09-02 10:01 UTC, akalipetis commented on README.md
> +- Poetry 1.2 on Python 3.10 and Buster: `ghcr.io/withlogicco/poetry:1.2-python-3.10-buster`
```suggestion
- Poetry 1.2.0: `ghcr.io/withlogicco/poetry:1.2.0`
- Poetry 1.2.0 on Python 3.10: `ghcr.io/withlogicco/poetry:1.2.0-python-3.10`
- Poetry 1.2.0 on Buster: `ghcr.io/withlogicco/poetry:1.2.0-buster`
- Poetry 1.2.0 on Python 3.10 and Buster: `ghcr.io/withlogicco/poetry:1.2.0-python-3.10-buster`
```

2022-09-02 10:01 UTC, akalipetis commented on README.md
> +![Poetry](https://img.shields.io/badge/Poetry-1.2-purple) ![Python](https://img.shields.io/badge/Python-3.10%20(default)%20%7C%203.9%20%7C%203.8%20%7C%203.7-blue) ![Variants](https://img.shields.io/b
```suggestion
![Poetry](https://img.shields.io/badge/Poetry-1.2.0-purple) ![Python](https://img.shields.io/badge/Python-3.10%20(default)%20%7C%203.9%20%7C%203.8%20%7C%203.7-blue) ![Variants](https://img.shields.io/badge/Variants-Buster%20(default)%20%7C%20Slim%20%7C%20Alpine-orange
```

2022-09-08 08:13 UTC, parisk commented on Dockerfile
> +RUN pip install poetry==${POETRY_VERSION}
Installing with `pip` is officially supported and looks like a better option, as described in both the manual[^1] and the CI[^2], where it states

> Unlike development environments, where making use of the latest tools is desirable, in a CI environment reproducibility should be made the priority.

[^1]: https://python-poetry.org/docs/#installing-manually
[^2]: https://python-poetry.org/docs/#ci-recommendations

2022-09-08 08:15 UTC, merged