Add tests for poetry
withlogicco/docker-poetry pull request #48
Opened 2024-01-30 10:07 UTC by gmargaritis

Resolves #8

2024-01-30 13:29 UTC, parisk requested changes
I would suggest taking a simpler approach on the CI level here, although the tests are  💯. A few suggestions:

- Run tests on the whole matrix on every push, so that we know our commits work as expected.
- If tests succeed, push image to GHCR tagged with `${github.sha}-{EXPECTED_RELEASE_TAG}` (e.g. `95db419-1.7.1-python-3.12-bookworm`)
- On release, tag the existing Git SHA tagged image on GHCR with the release version (e.g. `1.7.1-python-3.12-bookworm`)

2024-01-30 13:29 UTC, parisk commented on .github/workflows/release.yml
> +    runs-on: ubuntu-20.04
Let's bump this to use `ubuntu-latest`

2024-01-30 13:29 UTC, parisk commented on Dockerfile
> +COPY ./tests/tests.py /usr/src/app/tests.py
We do not want to make this part of our Dockerfile. We should either create a separate build target, or bind mount it, when we `docker run`. I suggest the former.

2024-01-31 15:34 UTC, gmargaritis commented
@parisk Let me know how to proceed from here. What changes do we want to make in the release workflow?

2024-01-31 17:08 UTC, parisk requested changes
I have added a few comments to tidy this up. We should also update the release workflow to just tag the images that already exist in the registry.

2024-01-31 17:08 UTC, parisk commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v3
Let's use the latest release: https://github.com/actions/checkout/releases/tag/v4.1.1

2024-01-31 17:08 UTC, parisk commented on .github/workflows/ci.yml
> +          --build-arg POETRY_VERSION=${{ env.POETRY_VERSION }} \
We can just use the latest build push action with `push: false` and `target: test`.

2024-01-31 17:08 UTC, parisk commented on .github/workflows/ci.yml
> +        uses: docker/login-action@v1
There's a more recent version

2024-01-31 17:08 UTC, parisk commented on .github/workflows/ci.yml
> +        uses: docker/build-push-action@v3.1.0
There is a more recent version: https://github.com/docker/build-push-action/releases/tag/v5.1.0

2024-02-01 10:45 UTC, gmargaritis commented
@parisk How does the pulling of existing images based on the git sha work? Wouldn't the git sha be different for the commit that triggered the `ci` workflow, from the one that triggered the `release` workflow?

2024-02-01 10:56 UTC, parisk commented
Nope, it's pretty much the same commit. All releases should happen on the `main` branch, for which the CI pipeline should always run: https://github.com/withlogicco/docker-poetry/pull/48/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR4-R6.

2024-02-01 12:14 UTC, parisk commented on .github/workflows/release.yml
> +          docker push $NEW_TAG
I suggest we use semantic variable names and reuse what we can

```suggestion
          TAG_SUFFIX="${{ matrix.python }}-${{ matrix.variant }}"
          GIT_SHA_TAG="${{ env.GHCR_IMAGE_REPOSITORY }}:${{ github.sha }}-${TAG_SUFFIX}"
          RELEASE_TAG="${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.POETRY_VERSION }}-python-${TAG_SUFFIX}"
          docker pull $GIT_SHA_TAG
          docker tag $GIT_SHA_TAG $RELEASE_TAG
          docker push $RELEASE_TAG
```

2024-02-01 12:15 UTC, parisk commented on .github/workflows/release.yml
> +          docker push $NEW_TAG
ditto: https://github.com/withlogicco/docker-poetry/pull/48/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R39-R43

2024-02-01 12:15 UTC, parisk commented on .github/workflows/release.yml
> +          docker push $NEW_TAG
ditto: https://github.com/withlogicco/docker-poetry/pull/48/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R39-R43

2024-02-01 12:15 UTC, parisk commented on .github/workflows/release.yml
> +          docker push $NEW_TAG
ditto: https://github.com/withlogicco/docker-poetry/pull/48/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R39-R43

2024-02-01 15:34 UTC, parisk approved these changes
LGTM 🦌

2024-02-01 15:34 UTC, merged